export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_ROLE:'SET_ROLE',
    SET_ACTIONS:'SET_ACTIONS',
    SET_NEW_USERS:'SET_NEW_USERS',
    SET_NUMBER_OF_USERS:'SET_NUMBER_OF_USERS',
    LOGGED_USER:'LOGGED_USER',
    SET_ISLOGGED_IN:'SET_ISLOGGED_IN'
  };